import { useEffect, useState } from "react";
import { returnsService } from "@/api";
import { apiMessages } from "@/components/rep/repOrderUtils";
import Modal from "@/components/ui/Modal";

export interface ReturnSourceItem { productVariantId: number; label: string; quantity: number }

export default function CreateReturnModal({ open, sourceType, sourceId, items, onClose, onSaved }: { open: boolean; sourceType: "SalesReturn" | "PurchaseReturn"; sourceId: number; items: ReturnSourceItem[]; onClose: () => void; onSaved: (message: string) => void }) {
  const [quantities, setQuantities] = useState<Record<number, number>>({}), [notes, setNotes] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setQuantities({}); setNotes(""); setError(""); } }, [open, sourceId]);
  if (!open) return null;
  const submit = async () => { const selected = items.map((item) => ({ product_variant_id: item.productVariantId, quantity: quantities[item.productVariantId] ?? 0 })).filter((item) => item.quantity > 0); if (!selected.length) return setError("اختر صنفًا واحدًا على الأقل وحدد كمية المردود."); setSaving(true); setError(""); try { const response = sourceType === "SalesReturn" ? await returnsService.createSales(sourceId, { items: selected, notes: notes.trim() || undefined }) : await returnsService.createPurchase(sourceId, { items: selected, notes: notes.trim() || undefined }); onSaved(response.message); } catch (reason) { setError(apiMessages(reason, "تعذر إنشاء المردود. راجع الكميات المتاحة للإرجاع.").join("، ")); } finally { setSaving(false); } };
  return <Modal open onClose={onClose} title={sourceType === "SalesReturn" ? "إنشاء مردود مبيعات" : "إنشاء مردود مشتريات"} size="lg" mobileFullscreen><div className="space-y-4">{error && <div className="rep-error">{error}</div>}<p className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-sm text-blue-900">{sourceType === "SalesReturn" ? "ستعود الكمية إلى المخزون وتُخفض مديونية الزبون." : "ستخرج الكمية من المخزون وتزداد مديونية الزبون."}</p><div className="max-h-[420px] space-y-2 overflow-y-auto">{items.map((item) => <label key={item.productVariantId} className="grid grid-cols-[1fr_110px] items-center gap-3 rounded-xl border p-3"><span><b className="block text-sm text-brand">{item.label}</b><small className="text-stone-500">الكمية الأصلية: {item.quantity}</small></span><span><span className="rep-label">كمية المردود</span><input className="rep-control" type="number" min="0" max={item.quantity} step="1" value={quantities[item.productVariantId] ?? 0} onChange={(event) => { const value = Math.max(0, Math.min(item.quantity, Number(event.target.value) || 0)); setQuantities((current) => ({ ...current, [item.productVariantId]: value })); }}/></span></label>)}</div><label><span className="rep-label">ملاحظات</span><textarea className="rep-control" rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="سبب المردود أو أي ملاحظة إضافية"/></label><div className="flex justify-end gap-2"><button className="btn-outline" onClick={onClose}>إلغاء</button><button className="btn-primary" disabled={saving} onClick={() => void submit()}>{saving ? "جاري الإنشاء…" : "تأكيد إنشاء المردود"}</button></div></div></Modal>;
}
