import type { PaginationResponseDto } from './common';

export type AccountKind = 'General' | 'Bank' | 'Cash' | 'CheckHolding' | 'Clearing' | 'OnlineSales' | 'StoreSales' | 'Returns' | 'Revenue' | 'PurchaseOffset' | 'Equity' | 'DebtOffset' | 'Expense';
export interface LedgerAccount { account_id: number; code: string; name: string; kind: AccountKind; account_number: string | null; phone: string | null; bank_parent_id: number | null; is_system: boolean; created_at: string; balance: string }
export interface SaleAccountOption { id: number; name: string; account_number?: string | null; phone?: string | null }
export interface StatementSourceItem { product_name: string; product_code: string; size: string; color: string; quantity: number; unit_price: string; unit_discount?: string; line_total: string; is_bonus?: boolean }
export interface StatementSourceDetails { kind: 'Order' | 'Purchase' | 'Return' | 'Payment' | 'CheckMovement'; reference_id: number; is_reversal: boolean; status?: string; return_type?: string; payment_type?: string; method?: string; action?: string; subtotal?: string; product_discount_total?: string; order_discount?: string; total?: string; amount?: string; base_amount?: string | null; exchange_rate?: string | null; currency?: { code: string; name: string } | null; check?: { number: string; due_date: string; bank_name: string | null; location: string } | null; items?: StatementSourceItem[]; return_number?: string; return_date?: string; purchase_id?: number | null; cancelled?: boolean; notes?: string | null }
export interface TreasuryLocation extends LedgerAccount { balance: string }
export interface CashAccountDto { account_id: number; name: string; balance_base: string; is_default: boolean }
export interface TreasuryOverview { total: string; locations: TreasuryLocation[] }
export interface VoucherInput { type: 'Receipt' | 'Disbursement' | 'Journal'; notes?: string; occurred_at?: string; lines: Array<{ account_id: number; debit?: number; credit?: number }> }
export type ManagedCheckLocation = 'TREASURY' | 'BANK' | 'COLLECTION' | 'ENDORSED_PARTY' | 'SOURCE_PARTY' | 'CASHED' | 'CANCELLED' | 'ISSUED' | 'CLEARED' | 'RETURNED_OUTGOING';
export interface ManagedCheckEvent { check_event_id: number; action: string; from_location: string | null; to_location: string; from_account_id: number | null; to_account_id: number | null; bank_account_id: number | null; party_account_id: number | null; journal_entry_id: number | null; reversal_journal_entry_id: number | null; operation_date: string; notes: string | null; details: unknown; created_by: number | null; created_at: string; cancelled_at: string | null; cancelled_by: number | null; cancel_reason: string | null; cancels_event_id: number | null }
export interface ManagedCheck { managed_check_id: number; payment_id: number; number: string; direction: 'Incoming' | 'Outgoing'; bank_name: string | null; original_amount: string; currency_id: number; exchange_rate: string; base_amount: string; received_date: string; due_date: string; source_account_id: number; source_account: { account_id: number; name: string }; location: ManagedCheckLocation; current_bank_account_id: number | null; current_party_account_id: number | null; created_by: number | null; created_at: string; updated_at: string; collected: boolean; due_status: 'Due' | 'NotDue'; payments: { payment_id: number; notes: string | null; account: { account_id: number; name: string } | null; currencies: { currency_id: number; code: string; name: string; symbol: string } | null }; events: ManagedCheckEvent[] }
export interface ManagedCheckEditDto { number?: string; bank_name?: string; bank_number?: string; branch_number?: string; account_number?: string; amount?: string; currency_id?: number; exchange_rate?: string; source_account_id?: number; bank_account_id?: number; received_date?: string; payment_notes?: string; due_date?: string; notes?: string }
export type ManagedCheckEditResult = Omit<ManagedCheck, 'payments' | 'events'>;
export type IncomingCheckMovementAction = 'DEPOSITED' | 'SENT_TO_COLLECTION' | 'RETURNED_FROM_BANK' | 'ENDORSED' | 'ENDORSEMENT_RETURNED' | 'RETURNED_TO_SOURCE' | 'RETRIEVED_FROM_SOURCE' | 'CASHED';
export interface IncomingCheckMovementDto { bank_account_id?: number; cash_account_id?: number; party_account_id?: number; operation_date?: string; notes?: string }
export interface CheckUndoDto { operation_date: string; reason?: string }
export interface OutgoingCheckMovementDto { operation_date: string }
export interface ManagedChecksResponse { items: ManagedCheck[]; pagination: PaginationResponseDto }
export interface ManagedChecksQuery { search?: string; location?: ManagedCheckLocation; due_status?: 'Due' | 'NotDue'; currency_id?: number; due_from?: string; due_to?: string; page?: number; limit?: number }
