import { useEffect, useState } from 'react';
import { customersService, type CustomerSelectionDto } from '@/api';
import { apiMessages } from '@/components/rep/repOrderUtils';

export default function CustomersPage({ onNavigate, basePath }: { onNavigate: (path: string) => void; basePath: string }) {
  const [items, setItems] = useState<CustomerSelectionDto[]>([]); const [search, setSearch] = useState('');
  const [error, setError] = useState(''); const [create, setCreate] = useState(false);
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { const controller = new AbortController(); customersService.list({ page: 1, limit: 100, search: search || undefined }, controller.signal).then((r) => setItems(r.customers)).catch((reason) => { if (!controller.signal.aborted) setError(apiMessages(reason, 'تعذر تحميل الجهات.').join('، ')); }); return () => controller.abort(); }, [search]);
  const submit = async () => { if (!name.trim() || !phone.trim() || saving) return; setSaving(true); try { await customersService.create({ name: name.trim(), phone: phone.trim() }); setCreate(false); setSearch(phone.trim()); setError(''); } catch (reason) { setError(apiMessages(reason, 'تعذر إنشاء الجهة.').join('، ')); } finally { setSaving(false); } };
  return <div className="space-y-5" dir="rtl"><header className="flex flex-wrap items-end justify-between gap-3 border-b pb-4"><div><h1 className="text-3xl font-black text-brand">بيانات الجهات</h1><p className="text-sm text-stone-500">للبحث في الاسم والهاتف. عمليات القبض والصرف تبدأ من <button className="font-bold text-gold-dark underline" onClick={() => onNavigate(`${basePath}/payments`)}>صفحة السندات</button>.</p></div><button className="btn-primary" onClick={() => setCreate(true)}>إضافة جهة</button></header><input className="rep-control max-w-lg" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="بحث بالاسم أو الهاتف" />{error && <div className="rep-error">{error}</div>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <button className="rounded-2xl border bg-white p-4 text-right hover:border-gold-dark" key={item.customer_id} onClick={() => onNavigate(`${basePath}/customers/${item.customer_id}`)}><b className="text-brand">{item.name}</b><p className="text-sm text-stone-500">{item.phone} · #{item.customer_id}</p></button>)}</div>{!items.length && !error && <p className="rounded-xl border bg-white p-6 text-center text-stone-500">لا توجد نتائج.</p>}
    {create && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form className="w-full max-w-md space-y-3 rounded-2xl bg-white p-5" onSubmit={(event) => { event.preventDefault(); void submit(); }}><h2 className="text-xl font-black">إضافة جهة</h2><label className="block"><span className="rep-label">الاسم</span><input className="rep-control" value={name} onChange={(event) => setName(event.target.value)} required /></label><label className="block"><span className="rep-label">الهاتف</span><input className="rep-control" value={phone} onChange={(event) => setPhone(event.target.value)} required /></label><div className="flex justify-end gap-2"><button type="button" className="btn-outline" onClick={() => setCreate(false)}>إلغاء</button><button className="btn-primary" disabled={saving}>{saving ? 'جارٍ الحفظ…' : 'حفظ'}</button></div></form></div>}
  </div>;
}
