import { useEffect, useState, type FormEvent } from 'react';
import { ChevronLeft, ChevronRight, Eye, Pencil, Plus } from 'lucide-react';
import { ordersService, type ApiOrderStatus, type OrderListItemResponseDto, type OrdersPaginationDto, type PaymentStatus } from '@/api';
import { OrderStatusBadge, PaymentStatusBadge } from './RepOrderUi';
import { apiMessages, formatMoney, formatOrderDate } from './repOrderUtils';
import { Skeleton } from '@/components/ui/Skeleton';
import EmptyState from '@/components/ui/EmptyState';
import { RepDateInput, RepSearchField, RepSelect } from './RepFormControls';
const emptyPagination: OrdersPaginationDto = { page: 1, limit: 10, total: 0, total_pages: 0 }; const defaultSort = 'created_at:desc';
export default function RepOrders({ onNavigate }: { onNavigate: (path: string) => void }) {
  const [orders, setOrders] = useState<OrderListItemResponseDto[]>([]); const [pagination, setPagination] = useState(emptyPagination); const [loading, setLoading] = useState(true); const [errors, setErrors] = useState<string[]>([]);
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [submittedSearch, setSubmittedSearch] = useState(''); const [status, setStatus] = useState(''); const [paymentStatus, setPaymentStatus] = useState(''); const [dateFrom, setDateFrom] = useState(''); const [dateTo, setDateTo] = useState(''); const [sort, setSort] = useState(defaultSort);
  useEffect(() => { const c = new AbortController(); const [sort_by, sort_order] = sort.split(':') as ['created_at' | 'total_amount', 'asc' | 'desc']; setLoading(true); setErrors([]); ordersService.listMine({ page, limit: 10, search: submittedSearch || undefined, status: status as ApiOrderStatus || undefined, payment_status: paymentStatus as PaymentStatus || undefined, date_from: dateFrom || undefined, date_to: dateTo || undefined, sort_by, sort_order }, c.signal).then((r) => { setOrders(r.orders); setPagination(r.pagination); }).catch((e) => { if (!c.signal.aborted) setErrors(apiMessages(e, 'تعذر تحميل الطلبات.')); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [dateFrom, dateTo, page, paymentStatus, sort, status, submittedSearch]);
  const submit = (e: FormEvent) => { e.preventDefault(); setPage(1); setSubmittedSearch(search.trim()); }; const change = (setter: (v: string) => void) => (v: string) => { setter(v); setPage(1); };
  const filtersActive = Boolean(search || submittedSearch || status || paymentStatus || dateFrom || dateTo || sort !== defaultSort); const clear = () => { setSearch(''); setSubmittedSearch(''); setStatus(''); setPaymentStatus(''); setDateFrom(''); setDateTo(''); setSort(defaultSort); setPage(1); };
  return <div className="space-y-6"><header className="rep-page-header"><div><p className="rep-eyebrow">سجل المبيعات</p><h1 className="rep-title">طلباتي</h1><p className="rep-subtitle">جميع طلبات الجملة المرتبطة بحسابك.</p></div><button onClick={() => onNavigate('/rep/products')} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-brand px-5 text-sm font-black text-white"><Plus className="h-5 w-5" /> إنشاء طلب</button></header>
    <section className="overflow-visible rounded-2xl border bg-white p-4 shadow-sm"><form onSubmit={submit} className="grid items-end gap-3 md:grid-cols-2 xl:grid-cols-[1.4fr_repeat(5,1fr)_auto]"><RepSearchField label="البحث" value={search} onChange={setSearch} placeholder="رقم الطلب أو العميل" /><RepSelect label="حالة الطلب" value={status} onChange={change(setStatus)} options={[{value:'',label:'كل الحالات'},{value:'Pending',label:'قيد الانتظار'},{value:'Completed',label:'مكتمل'},{value:'Cancelled',label:'ملغي'}]} /><RepSelect label="حالة الدفع" value={paymentStatus} onChange={change(setPaymentStatus)} options={[{value:'',label:'كل حالات الدفع'},{value:'Unpaid',label:'غير مدفوع'},{value:'PartiallyPaid',label:'مدفوع جزئيًا'},{value:'Paid',label:'مدفوع'}]} /><RepDateInput label="من تاريخ" value={dateFrom} onChange={change(setDateFrom)} max={dateTo || undefined} /><RepDateInput label="إلى تاريخ" value={dateTo} onChange={change(setDateTo)} min={dateFrom || undefined} /><RepSelect label="الترتيب" value={sort} onChange={change(setSort)} options={[{value:defaultSort,label:'الأحدث'},{value:'created_at:asc',label:'الأقدم'},{value:'total_amount:desc',label:'الأعلى قيمة'},{value:'total_amount:asc',label:'الأقل قيمة'}]} /><button className="min-h-11 rounded-xl bg-brand px-4 text-sm font-black text-white">بحث</button></form>{filtersActive && <button type="button" onClick={clear} className="mt-3 text-xs font-black text-gold-dark">مسح الفلاتر</button>}</section>
    {errors.length > 0 && <div className="rep-error">{errors.join('، ')}</div>}{loading ? <Skeleton className="h-96" /> : orders.length === 0 ? <div className="rounded-2xl border bg-white"><EmptyState title="لا توجد طلبات مطابقة" /></div> : <><div className="hidden overflow-x-auto rounded-2xl border bg-white shadow-sm xl:block"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-stone-50 text-stone-500"><tr>{['الطلب','العميل','التاريخ','الحالة','الدفع','الإجمالي','المدفوع','المتبقي','الإجراءات'].map((x)=><th key={x} className="whitespace-nowrap px-4 py-3 text-right">{x}</th>)}</tr></thead><tbody className="divide-y">{orders.map((o)=><tr key={o.id}><td className="px-4 py-4 font-black text-brand">#{o.id}</td><td className="px-4"><strong className="block">{o.customer.name}</strong><small dir="ltr">{o.customer.phone}</small></td><td className="whitespace-nowrap px-4">{formatOrderDate(o.created_at)}</td><td className="px-4"><OrderStatusBadge status={o.status}/></td><td className="px-4"><PaymentStatusBadge status={o.payment_status}/></td><td className="px-4">{formatMoney(o.total_amount)}</td><td className="px-4 text-emerald-700">{formatMoney(o.paid_amount)}</td><td className="px-4 font-black text-red-700">{formatMoney(o.remaining_amount)}</td><td className="px-4"><Actions order={o} onNavigate={onNavigate}/></td></tr>)}</tbody></table></div><div className="space-y-3 xl:hidden">{orders.map((o)=><article key={o.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><strong className="text-brand">#{o.id}</strong><OrderStatusBadge status={o.status}/></div><h2 className="mt-3 font-black">{o.customer.name}</h2><p className="text-xs text-stone-400">{formatOrderDate(o.created_at)}</p><div className="mt-4 grid grid-cols-3 gap-2 border-y py-3 text-center text-xs"><Amount label="الإجمالي" value={o.total_amount}/><Amount label="المدفوع" value={o.paid_amount}/><Amount label="المتبقي" value={o.remaining_amount}/></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><PaymentStatusBadge status={o.payment_status}/><Actions order={o} onNavigate={onNavigate} text/></div></article>)}</div></>}
    {pagination.total_pages > 1 && <div className="flex items-center justify-center gap-3"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="btn-outline"><ChevronRight className="h-4 w-4"/> السابق</button><span>{page} من {pagination.total_pages}</span><button disabled={page>=pagination.total_pages} onClick={()=>setPage(page+1)} className="btn-outline">التالي <ChevronLeft className="h-4 w-4"/></button></div>}</div>;
}
function Actions({order,onNavigate,text=false}:{order:OrderListItemResponseDto;onNavigate:(p:string)=>void;text?:boolean}) { return <div className="flex gap-3"><button onClick={()=>onNavigate(`/rep/orders/${order.id}`)} className={text?'text-sm font-black text-gold-dark':'rounded-lg bg-blue-50 p-2 text-blue-700'} aria-label="التفاصيل">{text?'عرض التفاصيل':<Eye className="h-4 w-4"/>}</button>{order.status==='Pending'&&<button onClick={()=>onNavigate(`/rep/orders/${order.id}/edit`)} className={text?'inline-flex items-center gap-1 text-sm font-black text-amber-700':'rounded-lg bg-amber-50 p-2 text-amber-700'} aria-label="تعديل"><Pencil className="h-4 w-4"/>{text&&'تعديل'}</button>}</div>; }
function Amount({label,value}:{label:string;value:string}) { return <div><span className="block text-stone-400">{label}</span><strong className="mt-1 block text-brand">{formatMoney(value)}</strong></div>; }
